//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROGMGMT.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROGMGMT.Resources.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}(From)を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorFormatDateFrom {
            get {
                return ResourceManager.GetString("ErrorFormatDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}の指定が不正です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorFormatDateFromTo {
            get {
                return ResourceManager.GetString("ErrorFormatDateFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索条件の取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorGetCondition {
            get {
                return ResourceManager.GetString("ErrorGetCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   進捗データの取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorGetMgmt {
            get {
                return ResourceManager.GetString("ErrorGetMgmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索結果の取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorGetSearchResult {
            get {
                return ResourceManager.GetString("ErrorGetSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザーの取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorGetUser {
            get {
                return ResourceManager.GetString("ErrorGetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたユーザー名またはパスワードが正しくありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorLogin {
            get {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSVファイルの出力に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ErrorOutputCsv {
            get {
                return ResourceManager.GetString("ErrorOutputCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}_{1:yyyyMMddHHmmss}.csv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FormatCsvFile {
            get {
                return ResourceManager.GetString("FormatCsvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   東罐興業_グラビア進捗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressGurabiaTokan {
            get {
                return ResourceManager.GetString("ProgressGurabiaTokan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   東洋製罐_グラビア進捗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressGurabiaToyo {
            get {
                return ResourceManager.GetString("ProgressGurabiaToyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   樹脂版進捗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressJushihan {
            get {
                return ResourceManager.GetString("ProgressJushihan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   刷版進捗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressSappan {
            get {
                return ResourceManager.GetString("ProgressSappan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製版進捗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProgressSeihan {
            get {
                return ResourceManager.GetString("ProgressSeihan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   進捗の登録に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegistFailure {
            get {
                return ResourceManager.GetString("RegistFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   進捗の登録に成功しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegistSuccess {
            get {
                return ResourceManager.GetString("RegistSuccess", resourceCulture);
            }
        }
    }
}
